# -*- coding: utf-8 -*-
"""Claa_06_09_2026_hc_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxqlGqp5FAP3u86p24y0YPPGk7aX1PFh
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import scipy
proj_path=os.getcwd()
file_path=proj_path+'/hc_data.xlsx'
print("File_path:",file_path)
df=pd.read_excel(file_path)
print(df)

"""HEIRARCHIAL CLUSTERING
1)TOP DOWN (DIVISIVE)
2)BOTTOM UP(AGGLOMERATIVE)
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

proj_path = os.getcwd()
file_path = proj_path + '/hc_data.xlsx'
print('File Path: ',file_path)

df = pd.read_excel(file_path)
print(df)

labels = list(df['Student ID'])

linked = linkage(df, 'single')

plt.figure(figsize=(5, 3))
plt.subplot(1,2,1)
plt.scatter(df['Student ID'],df['Marks'])
plt.grid()
plt.xlabel('--- ID --->')
plt.ylabel('--- Linkage --->')

plt.subplot(1,2,2)

dendrogram(linked,
            orientation='top',
            labels=labels,
            distance_sort='descending',
            show_leaf_counts=True)
plt.grid()
plt.show()