# -*- coding: utf-8 -*-
"""Class_work_16_08_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjsD83o8sR9e5tiOWm6kBgOs2XmjhZ7Q
"""

#OS -->Operating System
import os
import pandas as pd
import matplotlib.pyplot as plt
#getcwd--> get the current working directory
proj_path = os.getcwd()
print('Project Path : ', proj_path)

file_path = proj_path + '/test_data.xlsx'
print('File Path : ', file_path)

df = pd.read_excel(file_path)
print(df)

plt.scatter(df['x'],df['y'])
plt.show()

df['x']
df['y']

import os
import pandas as pd
import matplotlib.pyplot as plt
proj_path=os.getcwd()
print('Project Path:',proj_path)
file_path=proj_path+'/test_data.xlsx'
print('File Path:',file_path)
df=pd.read_excel(file_path)
print(df)
plt.scatter(df['x'],df['y'])
plt.show()