# -*- coding: utf-8 -*-
"""class_work_23_08_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MrQqlPIGEXaXuziSl6p_LJm-t8PBTozq

CONFUSION MATRIX
"""

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# 1. Define your true (actual) ground truth and predicted labels
y_true = [1,0,0,1,1,0,1,0,1,1]
y_pred = [1,0,1,0,1,0,0,1,0,1]

# 2. Define human-readable labels for your classes
class_names = ['0', '1']

# 3. Compute the numerical confusion matrix array
cm = confusion_matrix(y_true,y_pred)
print("Raw Confusion Matrix Array:")
print(cm)

# 4. Create and display the visual matrix plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues)

# 5. Show the plot window
plt.title("Model Evaluation Confusion Matrix")
plt.show()

"""FOR 3*3 MATRIX"""

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# 1. Define your true (actual) ground truth and predicted labels
y_true = [1,0,2,1,1,0,2,0,1,1]
y_pred = [1,0,1,0,2,0,0,1,0,2]

# 2. Define human-readable labels for your classes
class_names = ['0', '1','2']

# 3. Compute the numerical confusion matrix array
cm = confusion_matrix(y_true,y_pred)
print("Raw Confusion Matrix Array:")
print(cm)

# 4. Create and display the visual matrix plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues)

# 5. Show the plot window
plt.title("Model Evaluation Confusion Matrix")
plt.show()

"""IMPLEMENTING BY IMPORTING THE FILE cm_data.xlsx"""

import os
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
proj_path=os.getcwd()
print(proj_path)
file_path=proj_path+'/cm_data.xlsx'
print(file_path)
df=pd.read_excel(file_path)
y_true=list(df['x_pred'])
y_pred=list(df['y_pred'])
# 1. Define your true (actual) ground truth and predicted labels
y_true = [1,0,0,1,1,0,1,0,1,1]
y_pred = [1,0,1,0,1,0,0,1,0,1]

# 2. Define human-readable labels for your classes
class_names = ['0', '1']

# 3. Compute the numerical confusion matrix array
cm = confusion_matrix(y_true,y_pred)
print("Raw Confusion Matrix Array:")
print(cm)

# 4. Create and display the visual matrix plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues)

# 5. Show the plot window
plt.title("Model Evaluation Confusion Matrix")
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import pandas as pd
import os

proj_path = os.getcwd()
file_path = proj_path + '/cm_data.xlsx'

df = pd.read_excel(file_path)

# 1. Define your true (actual) ground truth and predicted labels
#y_true = [1,0,2,1,1,0,1,0,2,2]
#y_pred = [1,1,2,2,1,0,0,1,2,0]
y_true = list(df['x_pred'])
y_pred = list(df['y_pred'])

# 2. Define human-readable labels for your classes
class_names = ['0', '1'] # Changed from ['0', '1','2'] to match the 2x2 confusion matrix

# 3. Compute the numerical confusion matrix array
cm = confusion_matrix(y_true,y_pred)
print("Raw Confusion Matrix Array:")
print(cm)

# 4. Create and display the visual matrix plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap=plt.cm.Blues)

# 5. Show the plot window
plt.title("Model Evaluation Confusion Matrix")
plt.show()