# -*- coding: utf-8 -*-
"""Class_30_08_2026_lin_regdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGl1gyuYacebwpULKWxh-geKE5E9ebJq
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

proj_path = os.getcwd()
print('Project Path = ',proj_path)

file_path = proj_path + '/lin_reg_data.xlsx'
print('File Path = ',file_path)

df = pd.read_excel(file_path)
print(df)

plt.scatter(df['X'],df['Y'])
plt.xlabel('--- X --->')
plt.ylabel('--- Y --->')
plt.title('Scatter Plot: Y vs X')
plt.grid()

inp = df.drop('Y',axis=1)
target = df['Y']

regr = linear_model.LinearRegression()
regr.fit(inp,target)

c= list(regr.coef_)
print('Regression Coefficients [b1] =',regr.coef_)

print('Regression Intercept b0 = ',round(regr.intercept_,3))
print('Regression Equation:\t','y = ',round(regr.intercept_,3),' +',regr.coef_,'x')

y_pred = regr.predict(inp)

print('x\ty\ty_pred\tError')
error=0
for r in range(0,len(df)):
    e = round(df.loc[r,'Y'] - y_pred[r],1)
    print(df.loc[r,'X'],'\t',df.loc[r,'Y'],'\t',round(y_pred[r],1),'\t',e)
    error = error + e*e
mse = error/len(df)
print('MSE = ',mse)

plt.plot(inp,y_pred)
plt.show()

import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder

proj_path = os.getcwd()
print('Project Path = ',proj_path)

file_path = proj_path + '/bmi.xlsx'
print('File Path = ',file_path)

df = pd.read_excel(file_path)
print(df)

#To convert gender column into numerical column
# 1. Initialize the encoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
print(df)

import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder

proj_path = os.getcwd()
print('Project Path = ',proj_path)

file_path = proj_path + '/bmi.xlsx'
print('File Path = ',file_path)

df = pd.read_excel(file_path)
print(df)

#To convert gender column into numerical column
# 1. Initialize the encoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
print(df)

inp = df.drop('Index',axis=1)
target = df['Index']

regr = linear_model.LinearRegression()
regr.fit(inp,target)

c= list(regr.coef_)
print('Regression Coefficients [b1] =',regr.coef_)

print('Regression Intercept b0 = ',round(regr.intercept_,3))
print('Regression Equation:\t','y = ',round(regr.intercept_,3),' +',regr.coef_,'x')

y_pred = regr.predict(inp)

print('x\ty\ty_pred\tError')
error=0
for r in range(0,len(df)):
    e = round(df.loc[r,'Index'] - y_pred[r],1)
    #print(df.loc[r,'X'],'\t',df.loc[r,'Index'],'\t',round(y_pred[r],1),'\t',e)
    error = error + e*e
mse = error/len(df)
print('MSE = ',mse)
x = inp['Weight']
y = df['Index']
plt.scatter(x,y)
plt.plot(y_pred, y)
plt.show()