# -*- coding: utf-8 -*-
"""Class_work_12_09_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luKU1Wj5FeI-vYoWkF4PA6s0mVaRL2bP
"""

import os
import pandas as pd
import nltk
nltk.download('stopwords') # Download the stopwords corpus
#download(nltk('punkt'))
from nltk.tokenize import sent_tokenize, word_tokenize
import re
import numpy as np
import math
from nltk.corpus import stopwords


#Step-1:	get the document or set of sentences
s = 'I have my bank account in state bank of india. I am walking on a river bank.'
print('Doc. :',s)

#Step-2: 	put all stuff into small case
s = s.lower()
print('Doc: ',s)

#Step-3:	Sentence Tokenization
temp = s.split('.')
sent = []

n=1
for r in temp:
    if(len(r)>0):
        sent.append(r)
        print('Sentence-',n,': ',r)
        n=n+1

#Step-4: 	Words Tokenization
w=[]
for r in range(0,len(sent)):
    t = sent[r].split(' ')
    u=[]
    for k in t:
        if(len(k)>0):
            u.append(k)
    w.append(u)
    print('Words in sent-',r+1,':',w[r])

#Step-5:	Stop words removal
sw = stopwords.words('english')
print("\nStop Words = ",sw)

#Step-6:	Unique words identification
#Step-7: 	Stemming or Lemmatization
#Step-8:	Algorithms 	cosine similarity, TF-IDF

#Step-5:	Stop words removal
sw = stopwords.words('english')
#print("\nStop Words = ",sw)

def remove_stop_words(word_list, stopwords_list):
    filtered_words = [word for word in word_list if word not in stopwords_list]
    return filtered_words

words = []
print('\n')
for r in range(0, len(sent)):
    t = remove_stop_words(w[r],sw)
    words.append(t)
    print('Words in sent-',r+1,':',words[r])
#Step-6:	Unique words identification

uw = []
print('\n')
for r in range(0, len(sent)):
    t = list(set(words[r]))
    uw.append(t)
    print('Unique Words in sent-',r+1,':',uw[r])
#Step-7: 	Stemming or Lemmatization
#Step-8:	Algorithms 	cosine similarity, TF-IDF

import os
import pandas as pd
import nltk
#download(nltk('punkt'))
from nltk.tokenize import sent_tokenize, word_tokenize
import re
import numpy as np
import math
from nltk.corpus import stopwords

def remove_stop_words(w, sw):
    t=[]
    for r in w:
        if(r not in sw):
            t.append(r)
    return(t)

#Step-1:	get the document or set of sentences
s = 'I have my bank account in state bank of india. I am walking on a river bank.'
print('Doc. :',s)

#Step-2: 	put all stuff into small case
s = s.lower()
print('Doc: ',s)

#Step-3:	Sentence Tokenization
temp = s.split('.')
sent = []

print('\n')
n=1
for r in temp:
    if(len(r)>0):
        sent.append(r)
        print('Sentence-',n,': ',r)
        n=n+1

#Step-4: 	Words Tokenization
print('\n')
w=[]
for r in range(0,len(sent)):
    t = sent[r].split(' ')
    u=[]
    for k in t:
        if(len(k)>0):
            u.append(k)
    w.append(u)
    print('Words in sent-',r+1,':',w[r])

#Step-5:	Stop words removal
sw = stopwords.words('english')
#print("\nStop Words = ",sw)

words = []
print('\n')
for r in range(0, len(sent)):
    t = remove_stop_words(w[r],sw)
    words.append(t)
    print('Words in sent-',r+1,':',words[r])

#Step-6:	Unique words identification
uw = []
print('\n')
for r in range(0, len(sent)):
    t = list(set(words[r]))
    uw.append(t)
    print('Unique Words in sent-',r+1,':',uw[r])

#Step-7: 	Stemming or Lemmatization

#Step-8:	Algorithms  cosine similarity, TF-IDF
#Cosine Similarity

x = set(uw[0])
y = set(uw[1])
rvector = list(x.union(y))
print('rvector = ',rvector)

#Step-8	Cosine similarity
v1=[]
v2=[]

for w in rvector:
    if w in x: v1.append(1) # create a vector
    else: v1.append(0)
    if w in y: v2.append(1)
    else: v2.append(0)

print('V1 = ',v1)
print('V2 = ',v2)

c = 0
# cosine formula
for i in range(len(rvector)):
        c+= v1[i]*v2[i]
cosine = (round(c / float((sum(v1)*sum(v2))**0.5), 3))*100
print("similarity: ", cosine,'%')

import os
import pandas as pd
import nltk
#download(nltk('punkt'))
from nltk.tokenize import sent_tokenize, word_tokenize
import re
import numpy as np
import math
from nltk.corpus import stopwords

def remove_stop_words(w, sw):
    t=[]
    for r in w:
        if(r not in sw):
            t.append(r)
    return(t)

#Step-1:	get the document or set of sentences
s = 'I have my bank account in state bank of india. I am walking on a river bank.'
print('Doc. :',s)

#Step-2: 	put all stuff into small case
s = s.lower()
print('Doc: ',s)

#Step-3:	Sentence Tokenization
temp = s.split('.')
sent = []

print('\n')
n=1
for r in temp:
    if(len(r)>0):
        sent.append(r)
        print('Sentence-',n,': ',r)
        n=n+1

#Step-4: 	Words Tokenization
print('\n')
w=[]
for r in range(0,len(sent)):
    t = sent[r].split(' ')
    u=[]
    for k in t:
        if(len(k)>0):
            u.append(k)
    w.append(u)
    print('Words in sent-',r+1,':',w[r])

#Step-5:	Stop words removal
sw = stopwords.words('english')
#print("\nStop Words = ",sw)

words = []
print('\n')
for r in range(0, len(sent)):
    t = remove_stop_words(w[r],sw)
    words.append(t)
    print('Words in sent-',r+1,':',words[r])

#Step-6:	Unique words identification
uw = []
print('\n')
for r in range(0, len(sent)):
    t = list(set(words[r]))
    uw.append(t)
    print('Unique Words in sent-',r+1,':',uw[r])

#Step-7: 	Stemming or Lemmatization

#Step-8:	Algorithms 	cosine similarity, TF-IDF
#Cosine Similarity
x = list(sorted(set(uw[0])))
y = list(sorted(set(uw[1])))

print('x = ',x)
print('y = ',y)
# print('z = ',z) # This line was causing the NameError
rvector = set(x).union(set(y))

rvector = list(rvector)
rvector = sorted(rvector)
print('rvector = ',rvector)


#Step-8	Cosine similarity
v1=[]
v2=[]

for w in rvector:
    if w in x: v1.append(1) # create a vector
    else: v1.append(0)
    if w in y: v2.append(1)
    else: v2.append(0)

print('V1 = ',v1)
print('V2 = ',v2)

c = 0
# cosine formula
for i in range(len(rvector)):
        c+= v1[i]*v2[i]
cosine = (round(c / float((sum(v1)*sum(v2))**0.5), 3))*100
print("similarity: ", cosine,'%')