# -*- coding: utf-8 -*-
"""Classwork_05_09_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17i1W_8M4CjdA4YH34VfmxSeLDL9hzSEW
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

proj_path = os.getcwd()
print('Project path = ',proj_path)

file_path = proj_path + '/k_means_data.xlsx'
print('File path = ',file_path)

df = pd.read_excel(file_path)
print(df)

k=6
model = KMeans(n_clusters=k).fit(df)
centroids = model.cluster_centers_

plt.figure(figsize=(6, 4))
row=1
col = 2
print(centroids)
plt.subplot(row,col,1)
plt.scatter(df['X'], df['Y'], c= model.labels_, s=100, alpha=0.5)
plt.grid()

plt.subplot(row,col,2)
plt.scatter(df['X'], df['Y'], c= model.labels_, s=100, alpha=0.5)
plt.scatter(centroids[:, 0], centroids[:, 1], c='red', s=50)
plt.grid()

plt.show()