# -*- coding: utf-8 -*-
"""Class_work_22_08_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygoO_femONx_Aj3lRDK-wWm_Gf1mg6aS

Visualisation
"""

import os
import pandas as pd
import matplotlib.pyplot as plt

proj_path = os.getcwd()
print('Project Path : ', proj_path)

file_path = proj_path + '/test_data.xlsx'
print('File Path : ', file_path)

df = pd.read_excel(file_path)
print(df)

plt.scatter(df['x'], df['y'])
plt.show()

# OS --> Operating System
import os
import pandas as pd
import matplotlib.pyplot as plt

#getcwd --> get the current working Directory
proj_path = os.getcwd()
print('Project Path : ', proj_path)

file_path = proj_path + '/test_data.xlsx'
print('File Path : ', file_path)

df = pd.read_excel(file_path)
#df = pd.read_excel('C:\Users\FC0156AU\OneDrive\Desktop\class_work_batch_15/test_data.xlsx')
print(df)

plt.scatter(df['x'], df['y'])
plt.xlabel('--- x --->')
plt.ylabel('--- y --->')
plt.title('Scatter Plot')
plt.grid()
plt.show()

"""For line plot

"""

plt.plot(df['x'],df['y'])
plt.scatter(df['x'], df['y'])
plt.xlabel('--- x --->')
plt.ylabel('--- y --->')
plt.title('Scatter Plot')
plt.grid()
plt.show()

"""for bar plot"""

plt.bar(df['x'],df['y'])
plt.scatter(df['x'], df['y'])
plt.xlabel('--- x --->')
plt.ylabel('--- y --->')
plt.title('Scatter Plot')
plt.grid()
plt.show()

"""Pie chart"""

X=[1,3,5,6,7]
ex=[0,0,0,0.2,0]
ttl=['one','three','five','seven','eight']
plt.pie(X,labels=ttl,explode=ex)
plt.show()

"""Box and Whisker plot"""

X=[2,23,34,21,36,30,12,49]
plt.boxplot(X)
plt.show()

X=[30,20,21,23,24,25]
ex=[0,0,0,0.2,0,0]
ttl=['Mango','Apple','Banana','Papaya', 'Orange', 'Grape']
plt.pie(X,labels=ttl,e)
plt.show()