# -*- coding: utf-8 -*-
"""Classwork_29_08_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdd--C1jmlXD4FEWKGWapbF3pzmvj82g
"""

import os
import pandas as pd
proj_path=os.getcwd()
print(proj_path)
file_path=proj_path+'/knn_data.xlsx'
print(file_path)
df=pd.read_excel(file_path)
print(df)

import os
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

proj_path=os.getcwd()
print(proj_path)
file_path=proj_path+'/knn_data.xlsx'
print(file_path)
df=pd.read_excel(file_path)
print(df)
inp = df.drop('Results',axis=1)

target = df['Results']

k=3

knn = KNeighborsClassifier(n_neighbors=k)

knn.fit(inp, target)

d = {

'Sub. - 1' : 5,

'Sub. - 2' : 7

}

test_inp = pd.DataFrame([d])
print(test_inp)
print("Query Result = ",knn.predict(test_inp))